apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: jnphub21
    apps.open-cluster-management.io/git-path: Hibernating
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cluster-hibernation
  name: cluster-hibernation-subscription
  namespace: cluster-hibernation
spec:
  channel: >-
    cluster-hibernation-resource-ns-0/cluster-hibernation-resource-0
  placement:
    local: true
  timewindow:
    hours:
      - end: '07:10PM'
        start: '07:00PM'
    location: America/Toronto
    daysofweek:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
    windowtype: active